### PR TITLE
fix: handle extensions.json comments in vscode-web and code-server

### LINKED ISSUE #385: vscode-web: auto installing extensions fails if json has comments
When using the `vscode-web` module with `auto_install_extensions` set to true extensions will fail if your repo's `.vscode/extensions.json` file contains comments. 

This appears to be because `run.sh` executes `jq` (which doesn't directly support json with comments) against the file ([see here](https://github.com/coder/modules/blob/main/vscode-web/run.sh#L95)). Comments in `.vscode/extensions.json` are fairly common (for example, see the extensions.json in the [vscode repo](https://github.com/microsoft/vscode/blob/main/.vscode/extensions.json#L2)).

### PR DESCRIPTION
**Pull request by matifali**
Resolves #385

### CODE REVIEW

File: code-server/run.sh [hunk 1]
```diff
@@ -104,7 +104,8 @@ if [ "${AUTO_INSTALL_EXTENSIONS}" = true ]; then
 
   if [ -f "$WORKSPACE_DIR/.vscode/extensions.json" ]; then
     printf "🧩 Installing extensions from %s/.vscode/extensions.json...\n" "$WORKSPACE_DIR"
-    extensions=$(jq -r '.recommendations[]' "$WORKSPACE_DIR"/.vscode/extensions.json)
+    # Use sed to remove single-line comments before parsing with jq
+    extensions=$(sed 's|//.*||g' "$WORKSPACE_DIR"/.vscode/extensions.json | jq -r '.recommendations[]')
```
Comment (ThomasK33) [inline code-server/run.sh:108]: This is sufficient as a quick fix. However, since both scripts will have Node available, we may want to consider parsing and stringifying the string using Node, as that should also eliminate multiline comments and comments after a field or value. (or even use a third-party NPM package to do so).

**Review by ThomasK33 — APPROVED** [review]

File: code-server/run.sh (hunk 1 above)
Comment (matifali) [reply code-server/run.sh:108]: That would be great. We can also get rid of `jq` then.
